### ISSUE TITLE
Compile Plugin for Grafana on Windows 

### ISSUE THREAD

**Issue by muenchris** [Enapter/telemetry-grafana-datasource-plugin#29]
Is there an option to get this plugin for a Windows based installation of Grafana?
Since its written in GO, it should not be too complicated, right?

**Comment by rnovatorov** [comment]
Hi @muenchris, thank you for submitting the issue.

Currently we only build binaries for Linux, but I am pretty sure we could build binaries for Windows as well.

As for now the only available option for Windows is to use a Docker-based Grafana installation.

**Comment by muenchris** [comment]
Yes, I think the priority is docker first, then linux and lastly Windows. I have a very large Grafana installation on Windows displaying all my other energy data and would like to add the Enapter data to it. 
Also for industrial environments, Windows is still a very popular OS for SCADA and MES environments that IT departments like to use rather then Linux.
